### ISSUE TITLE
error: [Errno 30] Read-only file system: '/app/lib/python3.9/site-packages/easy-install.pth'

### ISSUE THREAD

**Issue by BigOakley** [FilBot3/com.gitlab.screenkey.screenkey#2]
# The Issue
When building the flatpak on OpenSUSE Tumbleweed 20220408 I get the following error
```
Adding screenkey 1.3 to easy-install.pth file
error: [Errno 30] Read-only file system: '/app/lib/python3.9/site-packages/easy-install.pth'
Error: module screenkey: Child process exited with code 1
make: *** [Makefile:9: build] Error 1
```
## Clone
```bash
oakley@mobbep:~/data/repos> git clone git@github.com:FilBot3/com.gitlab.screenkey.screenkey.git
Cloning into 'com.gitlab.screenkey.screenkey'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (19/19), done.
Receiving objects: 100% (29/29), 8.43 KiB | 4.22 MiB/s, done.
Resolving deltas: 100% (10/10), done.
remote: Total 29 (delta 10), reused 26 (delta 7), pack-reused 0
oakley@mobbep:~/data/repos> 
```

## Submodule Inits
```bash
oakley@mobbep:~/data/repos/com.gitlab.screenkey.screenkey> git submodule init
Submodule 'shared-modules' (https://github.com/flathub/shared-modules.git) registered for path 'shared-modules'
oakley@mobbep:~/data/repos/com.gitlab.screenkey.screenkey> git submodule update
Cloning into '/home/oakley/data/repos/com.gitlab.screenkey.screenkey/shared-modules'...
Submodule path 'shared-modules': checked out '1b470b7982aa820ab2c972c8242f860e83ab6971'
oakley@mobbep:~/data/repos/com.gitlab.screenkey.screenkey> 
```
## make deps
```bash
oakley@mobbep:~/data/repos/com.gitlab.screenkey.screenkey> make deps
flatpak --user install org.gnome.Platform//42 org.gnome.Sdk//42 --assumeyes
Looking for matches…
Skipping: org.gnome.Platform/x86_64/42 is already installed
Skipping: org.gnome.Sdk/x86_64/42 is already installed
oakley@mobbep:~/data/repos/com.gitlab.screenkey.screenkey>
```
## Make build

[screenkey_build.txt](https://github.com/FilBot3/com.gitlab.screenkey.screenkey/files/8788185/screenkey_build.txt)
[make build output gist](https://gist.github.com/BigOakley/647f94c73c77ad3375e12011bbf761a1)

And everything past this fails so no output for those.

**Comment by BigOakley** [comment]
Added a gist output along with the .txt file

**Comment by FilBot3** [comment]
When you run the following

```bash
make clean deps build package install
```

What is the output? Can you add that to the Gist or a new Gist?

**Comment by BigOakley** [comment]
> ```shell
> make clean deps build package install
> ```

The command fails at with the same error as running them in order individually. I can create a new gist if you like, but it's nothing different that I can see.

**Comment by FilBot3** [comment]
> > ```shell
> > make clean deps build package install
> > ```
> 
> The command fails at with the same error as running them in order individually. I can create a new gist if you like, but it's nothing different that I can see.

These are the results I am getting when I build the Flatpak. I'm not sure why it's not working on your system.

* https://gist.github.com/FilBot3/bf95c40b45f0493b1f843f3780a29fa9

**Comment by BigOakley** [comment]
> > > ```shell
> > > make clean deps build package install
> > > ```
> > 
> > 
> > The command fails at with the same error as running them in order individually. I can create a new gist if you like, but it's nothing different that I can see.
> 
> These are the results I am getting when I build the Flatpak. I'm not sure why it's not working on your system.
> 
>     * https://gist.github.com/FilBot3/bf95c40b45f0493b1f843f3780a29fa9

Here's the full output from the command, but it's no different. I also don't know why that is failing. Could be something related to btrfs possibly. It does do some weird things in specific circumstances a lot

[single command output](https://gist.github.com/BigOakley/e8d2c6ad79536a30fd1949f949e681c1)

**Comment by FilBot3** [comment]
Fedora 36 Silverblue uses BTRFS as well. The only thing I could think of is that you're missing some Flatpak dependency that's not explicitly called out, or you may have a filesystem modification that is a deviation from standard.

**Comment by BigOakley** [comment]
> Fedora 36 Silverblue uses BTRFS as well. The only thing I could think of is that you're missing some Flatpak dependency that's not explicitly called out, or you may have a filesystem modification that is a deviation from standard.

I was on the right track, but BTRFS isn't the issue. The drive that this repo is on is formatted NTFS. After my last comment I went back and checked my mount points, and knowing that NTFS is not great, I re-cloned the repo in a different location. Went through with no problems at all. 

Root cause of the issue: NTFS permissions were causing things to be stupid during the build task.

**Comment by FilBot3** [comment]
That's fun. Good to know. I'll close this issue now.
